### PR TITLE
337 update icdb

### LINKED ISSUE #337: Update ICBD page
- Remove speaker
- update time and date
- update activities

### PR DESCRIPTION
**Pull request by Voxanimus**
Remove speaker and guest, keep thumnail format.
Update texte accordingly to the current year

close #337

### CODE REVIEW

**Comment by s314cy** [comment]
> @s314cy @dialexo don't remember, is it safe to merge a new package-lock.json ?

ça dépend de la méta, généralement tu veux merge si tu as vérifié que tout fonctionne, que y a pas eu de changements shady du package.json et que le repo n'a pas gitignore le package-lock.json

le package-lock sert à ce que la CI et les devs puissent reproduire le state de la main branch (qui est fonctionnelle) avec tous les paquets à la bonne version

ça veut aussi dire que ça peut tout casser de merge un nouveau package-lock ^^

**Comment by dialexo** [comment]
> > @s314cy @dialexo don't remember, is it safe to merge a new package-lock.json ?
> 
> ça dépend de la méta, généralement tu veux merge si tu as vérifié que tout fonctionne, que y a pas eu de changements shady du package.json et que le repo n'a pas gitignore le package-lock.json

Yes, also note that the `package-lock.json` should definitely be commited (https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#using-locked-packages). If you gitignore it and don't pin the versions (which is the case by default with npm and yarn), you're vulnerable to packages that don't follow semver, supply-chain attacks, etc.

> le package-lock sert à ce que la CI et les devs puissent reproduire le state de la main branch (qui est fonctionnelle) avec tous les paquets à la bonne version

Not only CI and dev, but prod also, as it ensures that the dependency tree remains immutable in the whole pipeline.

> ça veut aussi dire que ça peut tout casser de merge un nouveau package-lock ^^

In general yes. Though by default npm / yarn will only update if there are no breaking changes (e.g. `^1.0.1` may get updated to `1.2.5` for example), again assuming that the relevant package is following semver, which is not guaranteed. 

So in the best case, we can automate dependency bumps with e.g. renovatebot, but this is only a good idea if the code is properly CI'd and tested, so that code paths that are affected by such changes are properly checked.

**Review by Robb-Fr — CHANGES_REQUESTED** [review]
Capture d’écran 2022-12-19 à 17 28 00
Could we maybe re-put placeholders images and reduce the number of empty cells, keeping one raw of alumni etc ? This looks buggy for external viewer

**Comment by Voxanimus** [comment]
> Could we maybe re-put placeholders images and reduce the number of empty cells, keeping one raw of alumni etc ? This looks buggy for external viewer

@DeepGreen1 has already done some commit about this view of the page. This is one of the reason why I hesitated to just close this PR and made change in a another one.

**Comment by Robb-Fr** [comment]
Yep ok for me, let's do this, do I destroy this PR?

**Comment by Voxanimus** [comment]
> Yep ok for me, let's do this, do I destroy this PR?

I think it would be easier and anyway we can just relink the issues with the new PR since there is still some modification to do.

**Review by NoeTerrier — APPROVED** [review]
super

**Pull request closed without merging**
