### PR TITLE
Add Jane Street, CLICoaching, SDF to events

### PR DESCRIPTION
**Pull request by s314cy**
Manque encore le **short text** et le **more info url** pour Jane Street et CLICoaching. On attend les news :)

### CODE REVIEW

**Comment by Robb-Fr** [comment]
Des news là dessus?

**Comment by s314cy** [comment]
@Robb-Fr need your review before merging

**Review by Robb-Fr — COMMENTED** [review]
Looks tinkiwinky to me (I'm building for testing)

**Review by Robb-Fr — APPROVED** [review]
Looks Pepa x Memories to me

**Pull request merged**
